# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

# .github/workflows/azure-python-deploy.yml
name: Build and deploy Python app to Azure Web App - sunshield

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read  # Required for actions/checkout

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      # 1) Set up Node to build the React frontend
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'  # or whatever version you prefer

      - name: Build React frontend
        run: |
          cd frontend/sun-shield
          npm install --legacy-peer-deps
          npm run build
          # Copy the build folder to the backend folder
          cp -r build ../../backend

      # 2) Set up Python and install dependencies
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Create and activate virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install Python dependencies
        run: pip install -r backend/requirements.txt

      # 3) Zip everything you need to run your backend (including the React build folder)
      - name: Zip artifact for deployment
        run: |
          zip -r release.zip backend

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write  # Required for requesting the JWT
      contents: read   # Required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_A9ADF073742D4B40B3978DB31FA44622 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_F8E6C0C683884326BD1E15A02260666A }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_0AE1E2F9529E457BB81A3C00849FFB10 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'sunshield'
          slot-name: 'Production'
